In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
import pickle
import numpy as np

In [2]:
X = pickle.load(open("X.pickle", "rb"))
y = pickle.load(open("y.pickle", "rb"))

X = X/11 # Normalise to between 0 and 1
print(X)

[[0.90909091 0.90909091 0.90909091]
 [0.54545455 0.45454545 0.45454545]
 [0.36363636 0.63636364 0.18181818]
 ...
 [0.90909091 0.90909091 0.90909091]
 [0.90909091 1.         0.72727273]
 [1.         0.27272727 0.27272727]]


In [4]:
model = Sequential()
model.add(tf.keras.layers.Dense(3)) # Input layer
model.add(tf.keras.layers.Dense(4, activation="relu")) # adds the first layer of the network
model.add(tf.keras.layers.Dense(4, activation="relu")) # adds the second layer of the network
model.add(tf.keras.layers.Dense(3, activation="relu"))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, batch_size=32, epochs=4, validation_split=0.2)
print("Done")
model.save("testingtesting-4-epochs.model")

Train on 652613 samples, validate on 163154 samples
Epoch 1/4
652613/652613 [==============================] - 19s 29us/sample - loss: 0.2206 - acc: 0.9175 - val_loss: 0.1856 - val_acc: 0.9364
Epoch 2/4
652613/652613 [==============================] - 17s 27us/sample - loss: 0.1854 - acc: 0.9253 - val_loss: 0.1886 - val_acc: 0.9184
Epoch 3/4
652613/652613 [==============================] - 17s 26us/sample - loss: 0.1846 - acc: 0.9250 - val_loss: 0.1853 - val_acc: 0.9267
Epoch 4/4
652613/652613 [==============================] - 17s 26us/sample - loss: 0.1844 - acc: 0.9252 - val_loss: 0.1854 - val_acc: 0.9213
Done
